storage_pool_name = "vagrant-pool"
default_ram = 512

nodes = [
  { :hostname => 'vm145-91', :ansible_playbook => 'gluster_nodes.yml', :shell_provisioner => 'fix_gw.sh', :ip => '192.168.145.91', :box => 'centos/7', :ram => 1024 },
  { :hostname => 'vm145-92', :ansible_playbook => 'gluster_nodes.yml', :shell_provisioner => 'fix_gw.sh', :ip => '192.168.145.92', :box => 'centos/7', :ram => 1024 },
  { :hostname => 'vm145-93', :ansible_playbook => 'gluster_nodes.yml', :shell_provisioner => 'fix_gw.sh', :ip => '192.168.145.93', :box => 'centos/7', :ram => 1024 },
]


Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = node[:box]

      if node[:windows] == "yes"
        nodeconfig.vm.guest = :windows
        # Change timout to 15 minutes
        nodeconfig.vm.boot_timeout = 900
        # Increase timeout for the winrm service
        #nodeconfig.winrm.timeout = 600
        nodeconfig.winrm.retry_limit = 200
        nodeconfig.winrm.retry_delay = 30
      end

      nodeconfig.vm.hostname = node[:hostname]
      if node[:ip]
        nodeconfig.vm.network :private_network, ip: node[:ip]
      end

      if node[:shell_provisioner]
        nodeconfig.vm.provision :shell, path: node[:shell_provisioner]
      end

      if node[:ansible_playbook]
        nodeconfig.vm.provision :ansible do |ansible|
          ansible.playbook = node[:ansible_playbook]
        end
      end

      nodeconfig.vm.provider :libvirt do |lv|
        lv.qemu_use_session = false
        lv.storage_pool_name = storage_pool_name
        lv.driver = "kvm"
        lv.uri = "qemu:///system"
        lv.memory = node[:ram] ? node[:ram] : default_ram
        lv.graphics_type = "spice"
        lv.storage :file, :size => '2G'
      end

    end
  end
end

