storage_pool_name = "vagrant-pool"
default_ram = 512

nodes = [
  { :hostname => 'samba-devel-template', :ansible_playbook => 'samba_devel_template.yml', :box => 'fedora/30-cloud-base', :ram => 1024 },
]


Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = node[:box]

      if node[:windows] == "yes"
        nodeconfig.vm.guest = :windows
        # Change timout to 15 minutes
        nodeconfig.vm.boot_timeout = 900
        # Increase timeout for the winrm service
        #nodeconfig.winrm.timeout = 600
        nodeconfig.winrm.retry_limit = 200
        nodeconfig.winrm.retry_delay = 30
      end

      nodeconfig.vm.hostname = node[:hostname]
      if node[:ip]
        nodeconfig.vm.network :private_network, ip: node[:ip]
      end

      if node[:shell_provisioner]
        nodeconfig.vm.provision :shell, path: node[:shell_provisioner]
      end

      if node[:ansible_playbook]
        nodeconfig.vm.provision :ansible do |ansible|
          ansible.playbook = node[:ansible_playbook]
          ansible.extra_vars = {
            #needed for F30+
            #see https://github.com/ansible/ansible/issues/54855
            ansible_python_interpreter: "/usr/bin/python3",
          }
        end
      end

      nodeconfig.vm.provider :libvirt do |lv|
        lv.storage_pool_name = storage_pool_name
        lv.driver = "kvm"
        lv.uri = "qemu:///system"
        lv.memory = node[:ram] ? node[:ram] : default_ram
        lv.graphics_type = "spice"
      end
    end
  end
end

